# Pages CMS Configuration
# Simple, git-based CMS for static sites

media:
  - name: media
    label: Media
    input: public/images
    output: /images
    path: /images
  - name: documents
    label: Documents (PDFs)
    input: public/documents
    output: /documents
    path: /documents

content:
  # Blog Posts
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
      - name: publishDate
        label: Publish Date
        type: date
      - name: author
        label: Author
        type: string
      - name: image
        label: Featured Image
        type: image
      - name: imageAlt
        label: Image Alt Text
        type: string
      - name: tags
        label: Tags
        type: list
        field:
          type: string
      - name: featured
        label: Featured Post
        type: boolean
      - name: body
        label: Content
        type: rich-text

  # Events
  - name: events
    label: Events
    type: collection
    path: src/content/events
    fields:
      - name: title
        label: Event Title
        type: string
      - name: description
        label: Description
        type: text
      - name: eventDate
        label: Event Date
        type: date
      - name: eventTime
        label: Event Time
        type: string
      - name: location
        label: Location
        type: string
      - name: image
        label: Featured Image
        type: image
      - name: imageAlt
        label: Image Alt Text
        type: string
      - name: registrationLink
        label: Registration Link
        type: string
      - name: isPast
        label: Past Event
        type: boolean
      - name: featured
        label: Featured Event
        type: boolean
      - name: body
        label: Event Details
        type: rich-text

  # Team Members
  - name: team
    label: Team Members
    type: collection
    path: src/content/team
    fields:
      - name: name
        label: Name
        type: string
      - name: role
        label: Role/Position
        type: string
      - name: bio
        label: Short Bio
        type: text
      - name: image
        label: Profile Image
        type: image
      - name: imageAlt
        label: Image Alt Text
        type: string
      - name: email
        label: Email
        type: string
      - name: linkedin
        label: LinkedIn Profile
        type: string
      - name: order
        label: Display Order
        type: number
      - name: body
        label: Full Bio
        type: rich-text

  # Documents
  - name: documents
    label: Documents
    type: collection
    path: src/content/documents
    fields:
      - name: title
        label: Document Title
        type: string
      - name: description
        label: Description
        type: text
      - name: documentDate
        label: Document Date
        type: date
      - name: category
        label: Category
        type: select
        options:
          values:
            - Meeting Minutes
            - Governance Documents
      - name: documentFile
        label: PDF Link (Google Drive or Dropbox)
        type: string
        hint: 'Paste the shareable link to your PDF (e.g., https://drive.google.com/file/d/...)'
      - name: fileSize
        label: File Size (optional)
        type: string
      - name: featured
        label: Featured Document
        type: boolean
      - name: body
        label: Additional Notes
        type: rich-text